Algoritmo "crescente"

Var

   x, y:inteiro

Inicio

      escreva("Digite dois números: ")
      leia(x)
      leia(y)
      
      enquanto x <> y faca
               se x > y entao
                  escreval("Decrescente!")
               senao
                    escreval("Crescente!")
               fimse
               
               escreva("Digite outros dois números: ")
               leia(x)
               leia(y)
      fimenquanto

Fimalgoritmo